### ISSUE TITLE
How to handle exiting server

### ISSUE THREAD

**Issue by kevinpostal** [armon/go-socks5#12]
I am not as familar with go as I would like to be. I was wondering if there was anyway to handle closing of the socks5 server?

I have seen examples like:

http://www.hydrogen18.com/blog/stop-listening-http-server-go.html

and 

https://rcrowley.org/articles/golang-graceful-stop.html

Was wondering if it would be possible to do the same with the socks5 server?

**Comment by armon** [comment]
@kevinpostal There is no shutdown method on this server, but you can pass in a `Listener` to `Serve` and call `Close` on the listener and the server will stop serving as well.

**Comment by kevinpostal** [comment]
@armon That is what I ended up doing! Thanks for the quick reply!
