### ISSUE TITLE
FR: Allow the proxy to hijack some net.Conn's to be serviced internally

### ISSUE THREAD

**Issue by twitchyliquid64** [armon/go-socks5#17]
In short, I want to make it possible for the proxy to hand off the connection to some go code to handle, rather than always proxy it out.

I know server.Dial exists, but I think thats a little messy + lots of wrapping+unwrapping layers of abstraction (for this use case).

1. The client connects to the proxy and issues a connect for a specific endpoint.
2. The connect request matches some internal state indicating it should be hijacked.
3. The server proceeds as normal, except instead of opening the remote connection and proxying the data, it passes off the net.Conn to a callback.

In my use case, I pass the net.Conn to a http.Server and serve proxy status pages.

I am happy to code this and send a PR, just wanted to make sure this is okay with you.

**Comment by twitchyliquid64** [comment]
I envision the API looking like this:

```go
conf := &socks5.Config{
   Hijacker: myHijackerFunction,
}

// myHijackerFunction returns True if the connection is being hijacked.
func myHijackerFunction(req *Request, conn *net.Conn) bool{
  if req.RemoteAddr.FQDN == 'proxystate' {
    handleProxyStateRequest(conn)
    return True
  }
  return False
}
```

**Comment by twitchyliquid64** [comment]
Implemented. Lemme play around with usage and implementation in prod before merge.

Thoughts? https://github.com/twitchyliquid64/go-socks5/commit/9398063b9e2ea7e0e57d93ab872be448d802c764

**Comment by armon** [comment]
@twitchyliquid64 Looks good, I would just simplify from `ShouldHijack` and `HandleHijack` to a single `Hijack` which returns `(bool, error)` with the boolean indicating if it did hijack.

**Comment by yamifr07** [comment]
@twitchyliquid64 Link is not working anymore. Could you upload it again?

**Comment by twitchyliquid64** [comment]
I ended up using goproxy instead.

**Comment by yamifr07** [comment]
@twitchyliquid64 Could you upload the example?

**Comment by twitchyliquid64** [comment]
Cant find it I'm afraid, sorry.

**Comment by thomasf** [comment]
I think you could add a hook somewhere in this function https://github.com/armon/go-socks5/blob/master/request.go#L119
