### ISSUE TITLE
Debug output written to stdout

### ISSUE THREAD

**Issue by svent** [armon/go-socks5#4]
I am currently testing your libary in a project and it works great so far, thanks for your work!

I noticed that it writes to stdout (via log in request.go/proxy(), see [here](https://github.com/armon/go-socks5/blob/e586115c2d6e11fb18e051d752360b4ffeb6eaa1/request.go#L310)), breaking the output of programs using it.

Is it possible to remove that or to make it configurable?

**Comment by armon** [comment]
@svent I'd be happy to merge a PR that adds a `logger *log.Logger` to the Config, and using that throughout instead of the global logger. That way you can use a logger that discards output if you'd like.

**Comment by svent** [comment]
Thanks for the quick feedback - that sounds good, I will create a PR for that.

**Comment by armon** [comment]
Closed by #5
